import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
  
        <div className={styles.center}>
          <h1>Charles Cabral</h1>
          <p>Front-end Developer</p>
          <a href="mailto:charles.cabral.neto@gmail.com">charles.cabral.neto@gmail.com</a>
        </div>
      </main>
    </>
  )
}
